name = "installer"
main = "./build/worker.mjs"
compatibility_date = "2024-09-14"

[build]
command = "make build-tinygo"

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 0.1 # 10% of requests are logged
